umstier von init.vim zu init.lua hat begonnen!

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -1,5 +1,5 @@
-# Lukes lf-Einstellungen (übersetzt von Sergius)
-
+# SARBS lf-Einstellungen
+# 11.11.2024
 
 # Hinweis zu Bildvorschauen
 # Für diejenigen, die Bildvorschauen wünschen, wie dieses System, gibt es vier Schritte zur
@@ -15,23 +15,24 @@
 #    als Alias gesetzt werden (`alias lf="lfub") oder, wenn er an eine Taste gebunden ist,
 #    sollte er direkt anstelle des normalen lf aufgerufen werden.
 
-# Grundlegende Variablen
-set shellopts '-eu'
-set ifs "\n"
-set scrolloff 10
-set icons
-set period 1
-set hiddenfiles ".*:*.aux:*.log:*.bbl:*.bcf:*.blg:*.run.xml"
-set cleaner '~/.config/lf/cleaner'
-set previewer '~/.config/lf/scope'
-set autoquit true
+# ==== Grundlegende Einstellungen ====
+set shellopts '-eu'         # Shell-Optionen: e=exit on error, u=error on undefined variables
+set ifs "\n"                # Internal Field Separator auf Newline setzen
+set scrolloff 10            # 10 Zeilen Abstand beim Scrollen zum Rand beibehalten
+set icons                   # Aktiviert die Anzeige von Icons
+set period 1                # Aktualisierungsintervall in Sekunden
+set hiddenfiles ".*:*.aux:*.log:*.bbl:*.bcf:*.blg:*.run.xml"    # Liste der versteckten Dateitypen
+set cleaner '~/.config/lf/cleaner'  # Skript zum Aufräumen der Vorschau
+set previewer '~/.config/lf/scope'  # Skript für die Dateivorschau
+set autoquit true           # Beendet lf automatisch beim Öffnen einer Datei
 
-# Befehle/Funktionen
+# ==== Hauptbefehle/Funktionen ====
+# Komplexer Öffnungsbefehl für verschiedene Dateitypen:
 cmd open ${{
-    case $(file --mime-type "$(readlink -f $f)" -b) in
+	case $(file --mime-type "$(readlink -f $f)" -b) in
 	application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) localc $fx ;;
 	image/vnd.djvu|application/pdf|application/postscript) setsid -f zathura $fx >/dev/null 2>&1 ;;
-        text/*|application/json|inode/x-empty|application/x-subrip) $EDITOR $fx;;
+	text/*|application/json|inode/x-empty|application/x-subrip) $EDITOR $fx;;
 	image/x-xcf) setsid -f gimp $f >/dev/null 2>&1 ;;
 	image/svg+xml) display -- $f ;;
 	image/*) rotdir $f | grep -i "\.\(png\|jpg\|jpeg\|gif\|webp\|avif\|tif\|ico\)\(_large\)*$" |
@@ -46,18 +47,20 @@ cmd open ${{
 	application/pdf|application/vnd.djvu|application/epub*) setsid -f zathura $fx >/dev/null 2>&1 ;;
 	application/pgp-encrypted) $EDITOR $fx ;;
 	application/vnd.openxmlformats-officedocument.wordprocessingml.document|application/vnd.oasis.opendocument.text|application/vnd.openxmlformats-officedocument.spreadsheetml.sheet|application/vnd.oasis.opendocument.spreadsheet|application/vnd.oasis.opendocument.spreadsheet-template|application/vnd.openxmlformats-officedocument.presentationml.presentation|application/vnd.oasis.opendocument.presentation-template|application/vnd.oasis.opendocument.presentation|application/vnd.ms-powerpoint|application/vnd.oasis.opendocument.graphics|application/vnd.oasis.opendocument.graphics-template|application/vnd.oasis.opendocument.formula|application/vnd.oasis.opendocument.database) setsid -f libreoffice $fx >/dev/null 2>&1 ;;
-        application/octet-stream) case ${f##*.} in
+		application/octet-stream) case ${f##*.} in
 			doc|docx|xls|xlsx|odt|ppt|pptx) setsid -f libreoffice $fx >/dev/null 2>&1 ;;
 			ghw) setsid -f gtkwave $f >/dev/null 2>&1 ;;
 			ts) setsid -f mpv $f -quiet >/dev/null 2>&1 ;;
 			*) setsid -f zathura $fx >/dev/null 2>&1 ;;
-	   	esac ;;
+			esac ;;
 	*) for f in $fx; do setsid -f $OPENER $f >/dev/null 2>&1; done;;
-    esac
+	esac
 }}
 
+# Verzeichnisse erstellen (mit Unterverzeichnissen)
 cmd mkdir $mkdir -p "$@"
 
+# Archivdateien extrahieren (zip, tar, etc.)
 cmd extract ${{
 	clear; tput cup $(($(tput lines)/3)); tput bold
 	set -f
@@ -82,6 +85,7 @@ cmd extract ${{
 	}
 }}
 
+# Dateien sicher löschen mit Bestätigungsdialog
 cmd delete ${{
 	clear; tput cup $(($(tput lines)/3)); tput bold
 	set -f
@@ -91,6 +95,7 @@ cmd delete ${{
 	[ $ans = "y" ] && rm -rf -- $fx
 }}
 
+# Dateien verschieben mit fzf-Zielauswahl
 cmd moveto ${{
 	clear; tput cup $(($(tput lines)/3)); tput bold
 	set -f
@@ -102,6 +107,7 @@ cmd moveto ${{
 	notify-send "🚚 Datei(en) verschoben." "Datei(en) wurden nach $dest verschoben."
 }}
 
+# Dateien kopieren mit fzf-Zielauswahl
 cmd copyto ${{
 	clear; tput cup $(($(tput lines)/3)); tput bold
 	set -f
@@ -113,70 +119,74 @@ cmd copyto ${{
 	notify-send "📋 Datei(en) kopiert." "Datei(en) wurden nach $dest kopiert."
 }}
 
+
 cmd setbg "$1"
 
+# Mehrere Dateien gleichzeitig umbenennen
 cmd bulkrename ${{
-    tmpfile_old="$(mktemp)"
-    tmpfile_new="$(mktemp)"
+	tmpfile_old="$(mktemp)"
+	tmpfile_new="$(mktemp)"
+	[ -n "$fs" ] && fs=$(basename -a $fs) || fs=$(ls)
+	echo "$fs" > "$tmpfile_old"
+	echo "$fs" > "$tmpfile_new"
+	$EDITOR "$tmpfile_new"
+	[ "$(wc -l < "$tmpfile_old")" -eq "$(wc -l < "$tmpfile_new")" ] || { rm -f "$tmpfile_old" "$tmpfile_new"; exit 1; }
+	paste "$tmpfile_old" "$tmpfile_new" | while IFS="$(printf '\t')" read -r src dst
+	do
+		[ "$src" = "$dst" ] || [ -e "$dst" ] || mv -- "$src" "$dst"
+	done
+	rm -f "$tmpfile_old" "$tmpfile_new"
+	lf -remote "send $id unselect"
+}}
 
-    [ -n "$fs" ] && fs=$(basename -a $fs) || fs=$(ls)
-
-    echo "$fs" > "$tmpfile_old"
-    echo "$fs" > "$tmpfile_new"
-    $EDITOR "$tmpfile_new"
-
-    [ "$(wc -l < "$tmpfile_old")" -eq "$(wc -l < "$tmpfile_new")" ] || { rm -f "$tmpfile_old" "$tmpfile_new"; exit 1; }
-
-    paste "$tmpfile_old" "$tmpfile_new" | while IFS="$(printf '\t')" read -r src dst
-    do
-        [ "$src" = "$dst" ] || [ -e "$dst" ] || mv -- "$src" "$dst"
-    done
-
-    rm -f "$tmpfile_old" "$tmpfile_new"
-    lf -remote "send $id unselect"
+# Musik auf das Android Handy kopieren
+cmd adbpull ${{
+	clear; tput cup $(($(tput lines)/3)); tput bold
+	set -f
+	clear; echo "Wohin auf das Handy übertragen?"
+	dest="/sdcard/Music"  # Standardzielordner auf dem Handy
+	for x in $fx; do
+		adb push "$x" "$dest" &&
+		notify-send "📱 Datei übertragen." "Datei $x wurde auf das Handy übertragen."
+	done
+	# Auswahl deaktivieren
+	lf -remote "send $id unselect"
 }}
 
 # Tastenbelegungen
-# Ctrl+f	Öffnet fzf (fuzzy finder) und wählt die ausgewählte Datei in lf aus.
-map <c-f> $lf -remote "send $id select \"$(fzf)\""
-# J		Öffnet fzf mit einer Liste von Lesezeichen-Verzeichnissen und wechselt zum ausgewählten Verzeichnis.
-map J $lf -remote "send $id cd $(sed -e 's/\s*#.*//' -e '/^$/d' -e 's/^\S*\s*//' ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | fzf)"
-map H cd ~	#Springt zum Home-Verzeichniss
-map g top
-map D delete
-map E extract
-map C copyto
-map M moveto
-# Ctrl+n	Startet den Befehl zum Erstellen eines neuen Verzeichnisses.
-map <c-n> push :mkdir<space>""<left>
-# Ctrl+r	Lädt die aktuelle Ansicht neu.
-map <c-r> reload
-# Ctrl+s 	Schaltet die Anzeige versteckter Dateien ein/aus.
-map <c-s> set hidden!
-# Enter 	Öffnet eine Shell im aktuellen Verzeichnis.
-map <enter> shell
-# x 		Führt die ausgewählte Datei als Befehl aus.
-map x $$f
-# X 		Führt die ausgewählte Datei als Befehl aus und wartet auf Beendigung.
-map X !$f
-# o 		Öffnet die Datei mit dem Standard-Programm.
-map o &mimeopen "$f"
-# O 		Fragt, mit welchem Programm die Datei geöffnet werden soll.
-map O $mimeopen --ask "$f"
-# A 		Startet die Umbenennung am Ende des Dateinamens.
-map A :rename; cmd-end
-# c 		Startet eine neue Umbenennung, löscht den vorhandenen Namen.
-map c push A<c-u>
-# I		Startet die Umbenennung am Anfang des Dateinamens.
-map I :rename; cmd-home
-# i 		Startet die Umbenennung vor der Dateierweiterung.
-map i :rename
-# a		Startet die Umbenennung nach der Dateierweiterung.
-map a :rename; cmd-right
-# B 		Startet die Massenumbenennung für mehrere ausgewählte Dateien.
-map B bulkrename
-# b		Setzt die ausgewählte Datei als Hintergrundbild.
-map b $setbg $f
+map <c-f> $lf -remote "send $id select \"$(fzf)\""  # Ctrl+f: Dateisuche mit fzf
+map J $lf -remote "send $id cd $(sed -e 's/\s*#.*//' -e '/^$/d' -e 's/^\S*\s*//' ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | fzf)"    # J: Zu Lesezeichen springen
+map H cd ~      # H: Zum Home-Verzeichnis
+map g top       # g: Zum Anfang der Liste
+
+# Ausschneiden-Auswahl aufheben
+map sc clear
+
+# Dateioperationen
+map D delete                # D: Löschen                (delete)
+map E extract               # E: Archiv extrahieren     (extract)
+map C copyto                # C: Kopieren nach...       (copy)
+map M moveto                # M: Verschieben nach...    (move)
+map <c-n> push :mkdir<space>""<left>    # Ctrl+n: neues Verzeichnis
+map <c-r> reload            # Ctrl+r: Ansicht neu laden (reload)
+map <c-s> set hidden!       # Ctrl+s: Versteckte Dateien ein/aus
+map <esc> unselect			# Ctrl+l hebt die Auswahl aller ausgewählten Dateien auf
+map A adbpull               # A: ADB Puch für Musik-Datei und/oder -Verzeichniss.
+map B bulkrename            # B: Startet die Massenumbenennung für mehrere ausgewählte Dateien.
+map b $setbg $f             # b: Setzt die ausgewählte Datei als Hintergrundbild.
+
+# Dateibearbeitung
+map <enter> shell           # Enter: Öffnet eine Shell im aktuellen Verzeichnis.
+map x $$f                   # x: Datei ausführen        (eXecute)
+map X !$f                   # X: Ausführen und warten   (eXecute)
+map o &mimeopen "$f"        # o: Mit Standardprogramm öffnen
+map O $mimeopen --ask "$f"  # O: Programm auswählen und ausführen
+
+# Umbenennen
+map c push A<c-u>           # c: Komplett umbenennen
+map I :rename; cmd-home     # I: Am Anfang umbenennen
+map i :rename               # i: Vor Erweiterung umbenennen
+map a :rename; cmd-right    # a: Nach Erweiterung umbenennen
 
 # Ausführungsrechte für ausgewählte Dateien entziehen
 map <c-y> $for f in $fx; do chmod -x "$f"; done && lf -remote "send $id reload" && lf -remote "send $id unselect"
@@ -184,31 +194,25 @@ map <c-y> $for f in $fx; do chmod -x "$f"; done && lf -remote "send $id reload" 
 # Ausführungsrechte für ausgewählte Dateien geben
 map <c-x> $for f in $fx; do chmod +x "$f"; done && lf -remote "send $id reload" && lf -remote "send $id unselect"
 
-
-# Ctrl+e	Bewegt den Cursor eine Zeile nach unten
-# map <c-e> down
-# Ctrl+y	Bewegt den Cursor eine Zeile nach oben
-# map <c-y> up
 # V Öffnet den Texteditor nvim (Neovim) im aktuellen Verzeichnis
 # map V push :!nvim<space>
 
-# W		Öffnet ein neues Terminal-Fenster im aktuellen Verzeichnis
+# W: Öffnet ein neues Terminal-Fenster im aktuellen Verzeichnis
 map W $setsid -f $TERMINAL >/dev/null 2>&1
 
-# U 		Kopiert den vollständigen Pfad der ausgewählten Datei(en) in die Zwischenablage
+# Zwischenablage
+# U: Vollständiger Pfad in Zwischenablage
 map U $printf "%s" "$fx" | xclip -selection clipboard
-# u 		Kopiert nur den Dateinamen (ohne Pfad) der ausgewählten Datei(en) in die Zwischenablage
+# u: Nur Dateiname in Zwischenablage
 map u $printf "%s" "$fx" | sed 's/.*\///' | xclip -selection clipboard
 # . (Punkt) 	Extrahiert eine YouTube-URL aus dem Dateinamen und kopiert sie in die Zwischenablage
 map . $printf "%s" "$fx" | sed -E 's/^.+\[/https:\/\/www.youtube.com\/watch?v=/' | sed -E 's/\]\..+//' | xclip -selection clipboard
 # (Größer-als-Zeichen): Ähnlich wie der vorherige Befehl, aber für Piped (eine alternative YouTube-Frontend) URLs
 map <gt> $printf "%s" "$fx" | sed -E 's/^.+\[/https:\/\/piped.video\/watch?v=/' | sed -E 's/\]\..+//' | xclip -selection clipboard
-# T 		Öffnet nsxiv (Simple X Image Viewer) im Thumbnail-Modus für das aktuelle Verzeichnis
-map T $nsxiv -t "$(pwd)" 	# öffnet den Thumbnailmodus
+# T: öffnet den nsxiv im Thumbnailmodus
+map T $nsxiv -t "$(pwd)"
 # Ctrl+l 	Hebt die Auswahl aller ausgewählten Dateien auf
 map <c-l> unselect
-
-
 
 # Lesezeichen einbinden
 source "~/.config/lf/shortcutrc"
